name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'

      - name: Print current directory
        run: pwd

      - name: List root directory contents
        run: ls -al

      - name: Verify Flutter setup
        run: flutter --version

      - name: Debugging: List all directories
        run: |
          echo "Listing all directories"
          find . -type d

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./

      - name: Run tests
        run: |
          flutter test --machine > test-results/output.json
        continue-on-error: true
        working-directory: ./

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/output.json
        working-directory: ./

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
        working-directory: ./