name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'

      - name: Verify Flutter setup
        run: flutter --version

      - name: Find and Set Project Directory
        id: set-directory
        run: |
          echo "Finding pubspec.yaml..."
          PROJECT_DIR=$(find . -name pubspec.yaml -exec dirname {} \;)
          echo "Found project directory: $PROJECT_DIR"
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Check for test directory and run tests
        run: |
          if [ -d "${{ env.PROJECT_DIR }}/test" ]; then
            echo "Running tests in the test directory..."
            flutter test
          else
            echo "No test directory found. Skipping tests."
          fi
        working-directory: ${{ env.PROJECT_DIR }}
        continue-on-error: true

      - name: Build APK
        run: flutter build apk --release
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Find APK Path
        id: find-apk
        run: |
          APK_PATH=$(find "${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/" -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "No APK found!"
            exit 1
          fi
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "Found APK at $APK_PATH"

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ${{ env.APK_PATH }}